

include $(scripts_dir)/Makefile.debug

#########################################################################
#
#  Host Test Code Build
#
#########################################################################

SHELL=/bin/sh

LIB_INC_PATH=../../../lib

CC=gcc
CPP=g++

HOST_EXEC_C = 	entl_packet_test_run.c
HOST_SUB_C = entl_state_machine.c

HOST_EXEC = $(addprefix ,$(HOST_EXEC_C:.c=))
HOST_INC = -I../../../include -I../../include -I. -I../entl_libs -I../entl_state_test -I../entl_state_test/alo_unit_test
HOST_FLAGS = -Wall -L${LIB_INC_PATH} -g -Wl,-rpath,'$$ORIGIN/../../../lib' -DPACKAGE_NAME="\"nfp-sim-tools\"" -DPACKAGE_VERSION="\"beta\""
HOST_LIBS = -lpcap -lnfp_hwdbg -lnfp -lrt -lnfp_common -ljansson -lz


# Compile Switch for Host code
HOST_FLAGS+= -DNETRONOME_HOST 

entl_packet_test_run: entl_packet_test_run.c ../entl_libs/entl_state_machine.c ../entl_state_test/entl_sm_unit_test/entl_sm_tester.c ../entl_libs/atomic_link_op.c ../entl_state_test/alo_unit_test/alo_tester.c ../entl_state_test/alo_unit_test/cyc_random.c
	$(CC) $(HOST_FLAGS) $(HOST_INC) -pthread -o $@ $^ $(HOST_LIBS) 

%.cpp.o: %.cpp
	$(CPP) $(HOST_FLAGS) $(HOST_INC) -c -o $@ $<

%.c.o: %.c
	$(CC) $(HOST_FLAGS) $(HOST_INC) -c -o $@ $<

%: %.c $(NFPLIB_DIR) $(NFSALLIB_DIR) $(NFPCPPLIB_DIR)
	$(CC) $(EX_FLAGS) $(EX_INC) -pthread -o $@ $< $(EX_LIBS)

clean:
	find . -name "*.c.o" -print -delete
	find . -name "*.c~" -print -delete
	find . -name "*.h~" -print -delete
	find . -name "*.obj" -print -delete
	rm -f Makefile~ core
	rm -f $(HOST_EXEC)

chip_setup: 
	@echo "Running chip setup, this may take some time..."
	@echo "Enabling island 8,32 clocks only"
	$(EXDIR)/load_me -b
	#$(EXDIR)/load_me -F -e 8,32
	$(EXDIR)/nbidma_setup
	$(EXDIR)/nbitm_setup
	$(BINDIR)/nfp-macinit -m0 -0$(ETCDIR)/macinit/1x100GE.json -1$(ETCDIR)/macinit/1x100GE.json
	@echo "loading firmware"
	$(BINDIR)/nfp-nffw $(ELF) load



