/* 
 * Earth Computing Network Link Device User API
 * Copyright(c) 2016 Earth Computing.
 *
 *  Author: Atsushi Kasuya
 *
 */

#ifndef _ECNL_USER_API_H_
#define _ECNL_USER_API_H_

#define ECNL_GENL_NAME "ECNL_Family"

#define NL_ECNL_MULTICAST_GOUP_LINKSTATUS		"status"
#define NL_ECNL_MULTICAST_GOUP_AIT				"ait"
#define NL_ECNL_MULTICAST_GOUP_DISCOVERY		"discovery"
#define NL_ECNL_MULTICAST_GOUP_TEST				"test"

/* attributes */
enum nl_ecnd_attributes {
	NL_ECNL_ATTR_UNSPEC,

	NL_ECNL_ATTR_DEVICE_NAME,
	NL_ECNL_ATTR_DEVICE_ID,
	NL_ECNL_ATTR_PORT_NAME,	
	NL_ECNL_ATTR_PORT_ID,	
	NL_ECNL_ATTR_LINK_STATE,
	NL_ECNL_ATTR_CURRENT_STATE,
	NL_ECNL_ATTR_CURRENT_I_KNOW,
	NL_ECNL_ATTR_CURRENT_I_SENT,
	NL_ECNL_ATTR_ERROR_COUNT,
	NL_ECNL_ATTR_ERROR_FLAG,
	NL_ECNL_ATTR_ERROR_PFLAG,
	NL_ECNL_ATTR_ERROR_STATE,
	NL_ECNL_ATTR_ERROR_I_KNOW,
	NL_ECNL_ATTR_ERROR_I_SENT,
	NL_ECNL_ATTR_ERROR_TIME_SEC,
	NL_ECNL_ATTR_ERROR_TIME_NSEC,
	NL_ECNL_ATTR_NUM_AIT_MESSAGES,
	NL_ECNL_ATTR_TABLE_SIZE,
	NL_ECNL_ATTR_TABLE_ID,
	NL_ECNL_ATTR_TABLE_LOCATION,
	NL_ECNL_ATTR_TABLE_CONTENT,
	NL_ECNL_ATTR_TABLE_CONTENT_SIZE,
	NL_ECNL_ATTR_TABLE_ENTRY,
	NL_ECNL_ATTR_TABLE_ENTRY_LOCATION,
	NL_ECNL_ATTR_PORT_NAMES,
	NL_ECNL_ATTR_DEVICE_U_ADDR,
	NL_ECNL_ATTR_DEVICE_L_ADDR,

	NL_ECNL_ATTR_AIT_MESSAGE,

	NL_ECNL_ATTR_DISCOVERING_MSG,

	NL_ECNL_ATTR_MSG_LENGTH,

	// NL_ECNL_ATTR_,

	__NL_ECNL_ATTR_AFTER_LAST,
	NL_ECNL_ATTR_MAX = __NL_ECNL_ATTR_AFTER_LAST - 1
};


/* commands */
enum nl_ecnd_commands {
	NL_ECNL_CMD_UNSPEC,

	NL_ECNL_CMD_ALLOC_DRIVER,

	NL_ECNL_CMD_GET_STATE,
	NL_ECNL_CMD_ALLOC_TABLE,
	NL_ECNL_CMD_FILL_TABLE,
	NL_ECNL_CMD_FILL_TABLE_ENTRY,
	NL_ECNL_CMD_SELECT_TABLE,
	NL_ECNL_CMD_DEALLOC_TABLE,
	NL_ECNL_CMD_GET_PORT_NAMES,
	NL_ECNL_CMD_MAP_PORTS,
	NL_ECNL_CMD_START_FORWARDING,
	NL_ECNL_CMD_STOP_FORWARDING,
	NL_ECNL_CMD_SEND_AIT_MESSAGE,
	NL_ECNL_CMD_RETRIEVE_AIT_MESSAGE,

	NL_ECNL_CMD_SEND_DISCOVER_MESSAGE,

	__NL_ECNL_CMD_AFTER_LAST,
	NL_ECNL_CMD_MAX = __NL_ECNL_CMD_AFTER_LAST - 1
};

#endif
